<%@ Page Title="" Language="C#" MasterPageFile="~/Layouts/MainMaster.Master" AutoEventWireup="true" CodeBehind="ShoppingCartPage.aspx.cs" Inherits="WebWareHouse.ShoppingCartPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="GridViewShoppingCart" runat="server" DataKeyNames="car_id" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" Height="334px" OnRowDeleting="GridViewShoppingCart_RowDeleting" Width="659px" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" ForeColor="Black" GridLines="None">
    
        <AlternatingRowStyle BackColor="PaleGoldenrod" />
    
        <Columns>
            <asp:TemplateField HeaderText="ID">  
             <ItemTemplate>  
                 <asp:Label ID="lblId" runat="server" Text='<%#Bind("car_id") %>'></asp:Label>  
             </ItemTemplate>  
         </asp:TemplateField>  
         <asp:TemplateField HeaderText="Title">  
             <ItemTemplate>  
                 <asp:Label ID="lblTitle" runat="server" Text='<%#Bind("car_title") %>'></asp:Label>  
             </ItemTemplate>  
         </asp:TemplateField>  
         <asp:TemplateField HeaderText="Price">  
             <ItemTemplate>  
                 <asp:Label ID="lblPrice" runat="server" Text='<%#Bind("car_price") %>'></asp:Label>  
             </ItemTemplate>  
         </asp:TemplateField>  
         <asp:TemplateField HeaderText="Special">  
             <ItemTemplate>  
                 <asp:Label ID="lblSpecial" runat="server" Text='<%#Bind("car_special") %>'></asp:Label>  
             </ItemTemplate>  
         </asp:TemplateField>
        </Columns>

        <FooterStyle BackColor="Tan" />
        <HeaderStyle BackColor="Tan" Font-Bold="True" />
        <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
        <SortedAscendingCellStyle BackColor="#FAFAE7" />
        <SortedAscendingHeaderStyle BackColor="#DAC09E" />
        <SortedDescendingCellStyle BackColor="#E1DB9C" />
        <SortedDescendingHeaderStyle BackColor="#C2A47B" />

    </asp:GridView>
</asp:Content>
